- icon: fa-lightbulb
  heading: Electrical appliances
  description: >
    Smart home, lighting, ceiling fans, smoke detectors, electrical panel labeling
- icon: fa-wrench
  heading: Kitchen & Bathroom
  description: >
    Plumbing repairs, toilet installation, shower repair, hot water heater flush
- icon: fa-screwdriver
  heading: Furniture assembly
  description: >
    Pergolas, outdoor storage, cabinets, vanities, TV wall mounts
- icon: fa-home
  heading: General upkeep
  description: >
    Snow removal, screen door repair, leaf blowing
